"""
Django settings for pteryx project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os

from pathlib import Path
from urllib.parse import parse_qs, urlparse



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_env_file(env_path):
    if not env_path.exists():
        return

    for raw_line in env_path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue

        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


_load_env_file(BASE_DIR / ".env")


def _env_bool(name, default=False):
    raw_value = os.environ.get(name)
    if raw_value is None:
        return default
    return raw_value.strip().lower() in {'1', 'true', 'yes', 'on'}


def _env_list(name, default=None):
    raw_value = os.environ.get(name, '').strip()
    if raw_value:
        return [item.strip() for item in raw_value.split(',') if item.strip()]
    return list(default or [])


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DEBUG', default=True)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', '').strip()
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = 'django-insecure-akel9unmkziy24u1tv=aut#d5v!%n3hp6z-cbo*#2^0dewk7$h'
    else:
        raise ValueError('SECRET_KEY must be set when DEBUG is false.')

ALLOWED_HOSTS = _env_list(
    'ALLOWED_HOSTS',
    default=['trexdormcon.com', 'www.trexdormcon.com', 'localhost', '127.0.0.1'],
)

CSRF_TRUSTED_ORIGINS = _env_list(
    'CSRF_TRUSTED_ORIGINS',
    default=['https://trexdormcon.com', 'https://www.trexdormcon.com'],
)

SITE_URL = os.environ.get('SITE_URL', 'https://trexdormcon.com').strip().rstrip('/')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'eventmanager.apps.EventmanagerConfig',
]

OIDC_RP_CLIENT_ID = os.environ.get('OIDC_RP_CLIENT_ID', '').strip()
OIDC_RP_CLIENT_SECRET = os.environ.get('OIDC_RP_CLIENT_SECRET', '').strip()
OIDC_ENABLED = bool(OIDC_RP_CLIENT_ID and OIDC_RP_CLIENT_SECRET)

if OIDC_ENABLED:
    INSTALLED_APPS.insert(INSTALLED_APPS.index('django.contrib.auth') + 1, 'mozilla_django_oidc')

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]
if OIDC_ENABLED:
    AUTHENTICATION_BACKENDS.insert(0, 'eventmanager.auth.PetrockOIDCBackend')

PETROCK_ISSUER = 'https://petrock.mit.edu'
OIDC_OP_AUTHORIZATION_ENDPOINT = f'{PETROCK_ISSUER}/touchstone/oidc/authorization'
OIDC_OP_TOKEN_ENDPOINT = f'{PETROCK_ISSUER}/oidc/token'
OIDC_OP_USER_ENDPOINT = f'{PETROCK_ISSUER}/oidc/userinfo'
OIDC_OP_JWKS_ENDPOINT = f'{PETROCK_ISSUER}/oidc/jwks'
OIDC_RP_SCOPES = 'openid email profile'
OIDC_RP_SIGN_ALGO = 'RS256'
OIDC_TOKEN_USE_BASIC_AUTH = True
OIDC_VERIFY_SSL = True

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/logged-out/'
LOGIN_URL = 'oidc_authentication_init' if OIDC_ENABLED else '/admin/login/'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
if OIDC_ENABLED:
    MIDDLEWARE.append('mozilla_django_oidc.middleware.SessionRefresh')

ROOT_URLCONF = 'pteryx.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'pteryx'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'eventmanager.context_processors.auth_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'pteryx.wsgi.application'


def _build_database_config():
    database_url = os.environ.get('DATABASE_URL', '').strip()
    if not database_url:
        return {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }

    parsed_url = urlparse(database_url)
    if parsed_url.scheme not in {'postgres', 'postgresql'}:
        raise ValueError('DATABASE_URL must use a postgres or postgresql scheme.')

    database_config = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': parsed_url.path.lstrip('/'),
        'USER': parsed_url.username or '',
        'PASSWORD': parsed_url.password or '',
        'HOST': parsed_url.hostname or '',
        'PORT': str(parsed_url.port or ''),
        'OPTIONS': {
            'sslmode': 'require',
        },
    }

    query_options = parse_qs(parsed_url.query)
    sslmode = query_options.get('sslmode', [None])[0]
    if sslmode:
        database_config['OPTIONS']['sslmode'] = sslmode

    if not database_config['PORT']:
        database_config.pop('PORT')

    return database_config


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': _build_database_config(),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

if DEBUG:
    STORAGES = {
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }
else:
    STORAGES = {
        'staticfiles': {
            'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
        },
    }
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# Outbound notification email (separate from Petrock/Touchstone user login).
from eventmanager.email_settings import normalize_gmail_app_password, resolve_email_backend

GMAIL_SENDER_EMAIL = os.environ.get('GMAIL_SENDER_EMAIL', 'mit.rex.events@gmail.com').strip()
GMAIL_APP_PASSWORD = normalize_gmail_app_password(os.environ.get('GMAIL_APP_PASSWORD', ''))
DEFAULT_FROM_EMAIL = GMAIL_SENDER_EMAIL
EMAIL_BACKEND = resolve_email_backend(
    gmail_app_password=GMAIL_APP_PASSWORD,
    debug=DEBUG,
)
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = GMAIL_SENDER_EMAIL
EMAIL_HOST_PASSWORD = GMAIL_APP_PASSWORD

