# Generated by Django 6.0.1 on 2026-01-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RexEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('dorm', models.CharField(max_length=20)),
                ('dorm_sub', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('email_notif', models.TextField()),
                ('location', models.CharField()),
                ('contact_name', models.CharField(max_length=50)),
                ('contact_email', models.CharField(max_length=20)),
                ('res_status', models.CharField(choices=[('AP', 'Approved'), ('PE', 'Pending'), ('DE', 'Denied'), ('FL', 'Flagged')], default='PE', max_length=2)),
                ('ehs_status', models.CharField(choices=[('AP', 'Approved'), ('PE', 'Pending'), ('DE', 'Denied'), ('FL', 'Flagged')], default='PE', max_length=2)),
                ('ad_status', models.CharField(choices=[('AP', 'Approved'), ('PE', 'Pending'), ('DE', 'Denied'), ('FL', 'Flagged')], default='PE', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=10)),
            ],
        ),
    ]
