# Generated by Django 6.0.1 on 2026-01-30 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='RexUser',
        ),
    ]
