# Generated by Django 6.0.1 on 2026-02-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0002_rename_user_rexuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rexevent',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='rexevent',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='rexevent',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rexevent',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
