# Generated by Django 6.0.1 on 2026-02-01 17:31

from django.db import migrations, models


def combine_date_and_time(apps, schema_editor):
    if schema_editor.connection.vendor != 'postgresql':
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("ALTER TABLE eventmanager_rexevent ADD COLUMN start_time_new TIMESTAMP WITH TIME ZONE;")
        cursor.execute("ALTER TABLE eventmanager_rexevent ADD COLUMN end_time_new TIMESTAMP WITH TIME ZONE;")
        cursor.execute("""
            UPDATE eventmanager_rexevent
            SET start_time_new =
                CASE
                    WHEN start_date IS NOT NULL THEN (start_date::timestamp + start_time::interval) AT TIME ZONE 'UTC'
                    ELSE NOW()
                END
        """)
        cursor.execute("""
            UPDATE eventmanager_rexevent
            SET end_time_new =
                CASE
                    WHEN end_date IS NOT NULL THEN (end_date::timestamp + end_time::interval) AT TIME ZONE 'UTC'
                    ELSE NOW()
                END
        """)
        cursor.execute("UPDATE eventmanager_rexevent SET start_time_new = NOW() WHERE start_time_new IS NULL;")
        cursor.execute("UPDATE eventmanager_rexevent SET end_time_new = NOW() WHERE end_time_new IS NULL;")
        cursor.execute("ALTER TABLE eventmanager_rexevent DROP COLUMN start_date;")
        cursor.execute("ALTER TABLE eventmanager_rexevent DROP COLUMN end_date;")
        cursor.execute("ALTER TABLE eventmanager_rexevent DROP COLUMN start_time;")
        cursor.execute("ALTER TABLE eventmanager_rexevent DROP COLUMN end_time;")
        cursor.execute("ALTER TABLE eventmanager_rexevent RENAME COLUMN start_time_new TO start_time;")
        cursor.execute("ALTER TABLE eventmanager_rexevent RENAME COLUMN end_time_new TO end_time;")


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0002_rename_user_rexuser'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(combine_date_and_time, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='rexevent',
                    name='end_date',
                ),
                migrations.RemoveField(
                    model_name='rexevent',
                    name='start_date',
                ),
                migrations.AlterField(
                    model_name='rexevent',
                    name='end_time',
                    field=models.DateTimeField(),
                ),
                migrations.AlterField(
                    model_name='rexevent',
                    name='start_time',
                    field=models.DateTimeField(),
                ),
            ],
        ),
    ]
