# Generated by Django 6.0.4 on 2026-05-01 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0003_remove_rexevent_end_date_remove_rexevent_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rexevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventmanager.rexuser'),
        ),
        migrations.AlterField(
            model_name='rexevent',
            name='contact_email',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='rexevent',
            name='location',
            field=models.CharField(max_length=100),
        ),
    ]
