# Generated by Django 6.0.4 on 2026-05-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0004_rexevent_created_by_alter_rexevent_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rexevent',
            name='dc_status',
            field=models.CharField(choices=[('AP', 'Approved'), ('PE', 'Pending'), ('DE', 'Denied'), ('FL', 'Flagged')], default='PE', max_length=2),
        ),
        migrations.AddField(
            model_name='rexuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='rexuser',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('DormCon', 'DormCon'), ('RES', 'RES'), ('EHS', 'EHS'), ('AD', 'AD')], max_length=10),
        ),
    ]
