# Generated by Django 6.0.4 on 2026-05-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0005_rexevent_dc_status_rexuser_email_alter_rexuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='rexevent',
            name='ad_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rexevent',
            name='dc_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rexevent',
            name='ehs_comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rexevent',
            name='res_comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
