# Generated by Django 6.0.4 on 2026-06-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventmanager', '0006_rexevent_ad_comment_rexevent_dc_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_event_editing', models.BooleanField(default=True, help_text='When disabled, creators cannot edit or delete their submitted events.')),
            ],
            options={
                'verbose_name': 'Site configuration',
                'verbose_name_plural': 'Site configuration',
            },
        ),
        migrations.AlterField(
            model_name='rexevent',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rexevent',
            name='dorm',
            field=models.CharField(choices=[('Baker House', 'Baker House'), ('Burton-Conner', 'Burton-Conner'), ('East Campus', 'East Campus'), ('MacGregor', 'MacGregor'), ('Maseeh Hall', 'Maseeh Hall'), ('McCormick Hall', 'McCormick Hall'), ('New House', 'New House'), ('New Vassar', 'New Vassar'), ('Random Hall', 'Random Hall'), ('Simmons Hall', 'Simmons Hall')], max_length=30),
        ),
    ]
